name: GitHub Actions CD
on: [push]

env:
  IMAGE_NAME: "student-manager"
  IMAGE_PREFIX: "marcinator"


jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]
      
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
      - name: Test the project before packing
        run: dotnet test StudentManagerTest 
      #- name: build docker image
      #  run: docker build -t marcinator/student-manager:latest  ./StudentManager/
      #- name: push image to repo
      #  run: docker push ${{ env.IMAGE_PREFIX }}/student-manager:latest
        
  Build:
    runs-on: ubuntu-latest
    needs: Test

    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        #- name: build docker image
        #  run: docker build -t marcinator/student-manager:latest  ./StudentManager/
        #- name: push image to repo
        #  run: docker push ${{ env.IMAGE_PREFIX }}/student-manager:latest
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
          images: ${{ env.IMAGE_PREFIX }}/${{env.IMAGE_NAME}}

      - name: Echo extracted data
        run: echo "${{ steps.meta.outputs.tags }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./StudentManager/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  Deploy:
    runs-on: ubuntu-latest
    needs: [Test,Build]
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: marcinator.com
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      - name: Checkout source code
        uses: actions/checkout@v3
      - name : test
        run : echo hello
      #- name: Deploy to the Kubernetes cluster
      #  uses: azure/k8s-deploy@v1
      #  with:
      #    namespace: default
      #    manifests: |
      #      kubernetes/deployment.yaml
      #      kubernetes/ingress.yaml
      #      kubernetes/service.yaml
      #    images: |
      #      ${{ env.IMAGE_PREFIX }}/${{env.IMAGE_NAME}}:${{ github.sha }}
